// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvJw8v0CayFan5Aqusw18ndGOlFH-JU3k',
    appId: '1:927880165414:web:c6c4bade6e8a56050c8ee7',
    messagingSenderId: '927880165414',
    projectId: 'assignment-d3c9c',
    authDomain: 'assignment-d3c9c.firebaseapp.com',
    storageBucket: 'assignment-d3c9c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGKhmYSgyg_QVCaEcUIl_QGf5lUt4qwd8',
    appId: '1:927880165414:android:c372e051439b7fe80c8ee7',
    messagingSenderId: '927880165414',
    projectId: 'assignment-d3c9c',
    storageBucket: 'assignment-d3c9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyJSdjreMsgibEKCTwCTdeQ0YVp2CacPs',
    appId: '1:927880165414:ios:a18966a4322d12390c8ee7',
    messagingSenderId: '927880165414',
    projectId: 'assignment-d3c9c',
    storageBucket: 'assignment-d3c9c.firebasestorage.app',
    iosBundleId: 'com.chessflutter.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyJSdjreMsgibEKCTwCTdeQ0YVp2CacPs',
    appId: '1:927880165414:ios:3242b96d15a0beb00c8ee7',
    messagingSenderId: '927880165414',
    projectId: 'assignment-d3c9c',
    storageBucket: 'assignment-d3c9c.firebasestorage.app',
    iosBundleId: 'com.example.chessGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvJw8v0CayFan5Aqusw18ndGOlFH-JU3k',
    appId: '1:927880165414:web:8f68b80f2272417e0c8ee7',
    messagingSenderId: '927880165414',
    projectId: 'assignment-d3c9c',
    authDomain: 'assignment-d3c9c.firebaseapp.com',
    storageBucket: 'assignment-d3c9c.firebasestorage.app',
  );
}
